In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing
import seaborn as sns # data visualization

import json # to read the JSON file from Yelp

# ignore filter warnings
import warnings
warnings.filterwarnings('ignore')

In [6]:
filename = "yelp_academic_dataset_business.json" 
df = pd.read_json(filename, lines=True) # import the .json file containing businesses data

In [7]:
print(f"The businesses dataset contains {df.shape[0]} businesses.")
df.head(5)

The restaurants dataset contains 150346 restaurants.

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [8]:
df.categories.head(20) # there are not only restaurants in the dataset

0     Doctors, Traditional Chinese Medicine, Naturop...
1     Shipping Centers, Local Services, Notaries, Ma...
2     Department Stores, Shopping, Fashion, Home & G...
3     Restaurants, Food, Bubble Tea, Coffee & Tea, B...
4                             Brewpubs, Breweries, Food
5     Burgers, Fast Food, Sandwiches, Food, Ice Crea...
6     Sporting Goods, Fashion, Shoe Stores, Shopping...
7                   Synagogues, Religious Organizations
8     Pubs, Restaurants, Italian, Bars, American (Tr...
9     Ice Cream & Frozen Yogurt, Fast Food, Burgers,...
10                 Department Stores, Shopping, Fashion
11           Vietnamese, Food, Restaurants, Food Trucks
12    American (Traditional), Restaurants, Diners, B...
13    General Dentistry, Dentists, Health & Medical,...
14          Food, Delis, Italian, Bakeries, Restaurants
15                    Sushi Bars, Restaurants, Japanese
16    Automotive, Auto Parts & Supplies, Auto Custom...
17    Vape Shops, Tobacco Shops, Personal Shopping, ...
18    Automotive, Car Rental, Hotels & Travel, Truck...
19                                  Korean, Restaurants
Name: categories, dtype: object

In [18]:
# We will make a list of all indices at which there is a business whose category does not
# contain the word "restaurant" and then we will drop those indices

substring = "Restaurant"
not_a_restaurant = []

for i in range (0, df.shape[0]):

    fullstring = json.dumps(df.categories[i])

    if substring not in fullstring :
        not_a_restaurant.append(i)

df_restaurants = df.drop(not_a_restaurant, axis=0).reset_index()

In [19]:
df_restaurants.shape

(52286, 15)

In [20]:
bars = []
for i in range (0, df_restaurants.shape[0]):

    fullstring = json.dumps(df_restaurants.categories[i])

    if "Bars" in fullstring : 
        bars.append(i)

df_restaurants = df_restaurants.drop(bars, axis=0).reset_index()

In [21]:
df_restaurants.shape

(41352, 16)

In [22]:
print(f"The dataset contains {df.shape[0]} businesses of which {df_restaurants.shape[0]} are restaurants.")

The dataset contains 150346 businesses of which 41352 are restaurants.

In [23]:
df_restaurants.groupby(by='categories').count().sort_values(by='index', ascending=False).head(50)

,level_0,index,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,hours
categories,,,,,,,,,,,,,,,
"Restaurants, Pizza",935,935,935,935,935,935,935,935,935,935,935,935,935,923,618
"Pizza, Restaurants",823,823,823,823,823,823,823,823,823,823,823,823,823,809,536
"Restaurants, Mexican",728,728,728,728,728,728,728,728,728,728,728,728,728,720,523
"Restaurants, Chinese",708,708,708,708,708,708,708,708,708,708,708,708,708,699,479
"Mexican, Restaurants",672,672,672,672,672,672,672,672,672,672,672,672,672,656,496
"Chinese, Restaurants",651,651,651,651,651,651,651,651,651,651,651,651,651,642,447
"Italian, Restaurants",328,328,328,328,328,328,328,328,328,328,328,328,328,323,239
"Restaurants, Italian",285,285,285,285,285,285,285,285,285,285,285,285,285,283,223
"Restaurants, American (New)",247,247,247,247,247,247,247,247,247,247,247,247,247,246,165
"American (New), Restaurants",235,235,235,235,235,235,235,235,235,235,235,235,235,233,151
"American (Traditional), Restaurants",203,203,203,203,203,203,203,203,203,203,203,203,203,201,106
"Restaurants, American (Traditional)",188,188,188,188,188,188,188,188,188,188,188,188,188,186,118
"Restaurants, Fast Food, Burgers",177,177,177,177,177,177,177,177,177,177,177,177,177,173,157
"Restaurants, Burgers, Fast Food",154,154,154,154,154,154,154,154,154,154,154,154,154,154,132
"Thai, Restaurants",152,152,152,152,152,152,152,152,152,152,152,152,152,149,128
"Restaurants, Vietnamese",146,146,146,146,146,146,146,146,146,146,146,146,146,144,122
"Fast Food, Restaurants, Burgers",143,143,143,143,143,143,143,143,143,143,143,143,143,143,132
"Barbeque, Restaurants",143,143,143,143,143,143,143,143,143,143,143,143,143,142,110
"Restaurants, Thai",140,140,140,140,140,140,140,140,140,140,140,140,140,140,115
"Restaurants, Barbeque",140,140,140,140,140,140,140,140,140,140,140,140,140,140,112
"Seafood, Restaurants",136,136,136,136,136,136,136,136,136,136,136,136,136,131,96
"Italian, Restaurants, Pizza",135,135,135,135,135,135,135,135,135,135,135,135,135,133,109
"Restaurants, Sandwiches",133,133,133,133,133,133,133,133,133,133,133,133,133,131,87
"Restaurants, Sandwiches, Fast Food",129,129,129,129,129,129,129,129,129,129,129,129,129,129,111
"Burgers, Restaurants, Fast Food",128,128,128,128,128,128,128,128,128,128,128,128,128,127,118
"Restaurants, Seafood",127,127,127,127,127,127,127,127,127,127,127,127,127,125,89
"Vietnamese, Restaurants",126,126,126,126,126,126,126,126,126,126,126,126,126,125,98
"Sandwiches, Restaurants",123,123,123,123,123,123,123,123,123,123,123,123,123,123,84
"Sandwiches, Restaurants, Fast Food",123,123,123,123,123,123,123,123,123,123,123,123,123,123,94
"Burgers, Fast Food, Restaurants",119,119,119,119,119,119,119,119,119,119,119,119,119,119,111
"Pizza, Restaurants, Italian",119,119,119,119,119,119,119,119,119,119,119,119,119,119,99
"Restaurants, Italian, Pizza",117,117,117,117,117,117,117,117,117,117,117,117,117,116,101
"Indian, Restaurants",115,115,115,115,115,115,115,115,115,115,115,115,115,114,96
"Restaurants, Indian",115,115,115,115,115,115,115,115,115,115,115,115,115,113,99
Restaurants,114,114,114,114,114,114,114,114,114,114,114,114,114,109,11
"Restaurants, Breakfast & Brunch",104,104,104,104,104,104,104,104,104,104,104,104,104,100,74
"Italian, Pizza, Restaurants",103,103,103,103,103,103,103,103,103,103,103,103,103,100,87
"Restaurants, Diners",101,101,101,101,101,101,101,101,101,101,101,101,101,101,59
"Restaurants, Pizza, Italian",100,100,100,100,100,100,100,100,100,100,100,100,100,100,86
"Diners, Restaurants",99,99,99,99,99,99,99,99,99,99,99,99,99,97,59
"Breakfast & Brunch, Restaurants",98,98,98,98,98,98,98,98,98,98,98,98,98,94,63
"Pizza, Italian, Restaurants",94,94,94,94,94,94,94,94,94,94,94,94,94,93,80
"Fast Food, Burgers, Restaurants",94,94,94,94,94,94,94,94,94,94,94,94,94,94,84
"Restaurants, Burgers",91,91,91,91,91,91,91,91,91,91,91,91,91,90,58
"Japanese, Restaurants",88,88,88,88,88,88,88,88,88,88,88,88,88,88,53
"Sandwiches, Fast Food, Restaurants",83,83,83,83,83,83,83,83,83,83,83,83,83,82,61
"Restaurants, Japanese",83,83,83,83,83,83,83,83,83,83,83,83,83,82,54
"Burgers, Restaurants",83,83,83,83,83,83,83,83,83,83,83,83,83,82,52
"Restaurants, Delis",80,80,80,80,80,80,80,80,80,80,80,80,80,80,54
"Restaurants, Steakhouses",78,78,78,78,78,78,78,78,78,78,78,78,78,75,61

In [28]:
df_restaurants.drop(columns=['level_0', 'index'], inplace=True)

In [29]:
# Take a sample of 10 000 restaurants

df_restaurants_sample = df_restaurants.sample(n=10000, random_state=42, replace=False).reset_index()

In [33]:
df_restaurants_sample.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,cHZ1FUswyko119EkV_9aNQ,Upper Crust Pizza,1909 E Grant Rd,Tucson,AZ,85719,32.250429,-110.943524,3.5,180,1,"{'BikeParking': 'True', 'RestaurantsPriceRange...","Salad, Pizza, Chicken Wings, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
1,bj0RCI6nDYcaJfWQk377Zw,Noodles & Company,903 Indiana Ave,Indianapolis,IN,46202,39.779672,-86.172865,3.5,84,1,"{'GoodForKids': 'True', 'BusinessAcceptsCredit...","Comfort Food, Fast Food, Specialty Food, Pasta...","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
2,BO9a-N3jvJyjoL524hzoSQ,Oscar's Taco Shop,331 Sam Ridley Pkwy W,Smyrna,TN,37167,35.987076,-86.547369,4.0,82,1,"{'BikeParking': 'False', 'HasTV': 'True', 'Cat...","Sandwiches, Restaurants, Mexican, Tex-Mex","{'Monday': '0:0-0:0', 'Tuesday': '10:0-21:0', ..."
3,dOznUZMHH1YxtWfz8O3GOA,Pasadena Bar & Grill,796 Pasadena Ave S,Saint Petersburg,FL,33707,27.762600,-82.734616,4.5,9,1,"{'GoodForKids': 'False', 'HasTV': 'True', 'Res...","American (Traditional), Restaurants, Sandwiche...",None
4,0u7UZC-5t_v8AS8AXTFASw,About Hotpot,125 Sansom Walkway,Philadelphia,PA,19106,39.947642,-75.143421,3.5,78,0,"{'WheelchairAccessible': 'False', 'HappyHour':...","Chinese, Hot Pot, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '11:0-22:0', ..."

In [34]:
filename = "yelp_academic_dataset_review.json"

n = sum(1 for line in open(filename, encoding="utf8"))-1  # Calculate number of rows in file
print("There are " + str(n) + " lines in the reviews file.")

There are 6990279 lines in the reviews file.

In [30]:
reader = pd.read_json(filename, lines=True, chunksize=100000) # initialize the json reader

In [31]:
df_reviews = pd.DataFrame() # initialize an empty dataframe

In [32]:
# Uncomment the below code to read in 7 million reviews, 43 minutes execution time
# The result of the code is saved in "reviews_for_sample_of_restaurants.csv" to avoid re-running the reader

# for chunk in reader : 
#     df_reviews = df_reviews.append(chunk)

In [33]:
df_reviews

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

In [35]:
# We keep only the reviews for our previous sample of 10 000 restaurants

reviews_for_sample_of_restaurants = df_reviews[df_reviews['business_id'].isin(df_restaurants_sample['business_id'])]

NameError: name 'df_reviews' is not defined

In [36]:
reviews_restaurants_extracted = pd.read_csv('reviews_restaurants_extracted.csv')
reviews_for_sample_of_restaurants = reviews_restaurants_extracted[reviews_restaurants_extracted['business_id'].isin(df_restaurants_sample['business_id'])]

In [37]:
reviews_for_sample_of_restaurants.shape

(156067, 9)

In [45]:
# We save the dataframe of reviews for the sample of restaurants as a .csv

reviews_for_sample_of_restaurants.to_csv("reviews_restaurants_extracted.csv", index=False)

In [38]:
# Keep only the bad reviews

bad_reviews = reviews_for_sample_of_restaurants[reviews_for_sample_of_restaurants["stars"]<3]

In [39]:
print("Shape of dataframe : " + str(bad_reviews.shape))
bad_reviews.head(5)

Shape of dataframe : (32593, 9)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
46,22n_UbOS_iqKKR3IrYhNGw,N1gb_Cx98QrcfA4CPrkY2w,QkyEr9j7il9lJqseTbPe5w,1,1,0,0,"I went here when if first opened, and have nev...",2013-05-29 02:17:04
56,ULzbgT5SPThiMOoo4a_Adw,veBX5roHQLNnQ1rTtNh_gg,aJvxWyQIG5OLfBw3qAe8xA,2,0,0,0,"Ordered Caramel frappe at Drive thru, BIG MIST...",2017-12-29 19:38:31
57,_Dkml_CfMMb_wWeGpFtczg,TRFTDMJegE6DituEKBpEKQ,W6S482dRQ_9nCcLjfv8VNg,1,0,0,0,Food was great. But very disappointed with the...,2016-07-04 04:17:15
83,9iSPQRg-oE525tze73mx4w,m9M_VU5Q3JpgrP9NFZFkQg,SDF1usj2mnUNqbIy4JBQTQ,1,0,0,0,Ordered an iced mocha and an iced white choco...,2014-08-11 00:51:07
114,j1eC52fAQFNqk0ZzSxyq6g,k5Lv0ZcY4R-uLsBbbqsP_w,LT4A5jVMURvH_DKdr7A91w,1,0,0,0,I'm a Barbecue judge and this ain't barbecue. ...,2015-09-23 23:59:01

In [ ]:
# drop_duplicates(inplace=True)

In [41]:
bad_reviews[['stars', 'text']].to_csv("bad_reviews.csv", index=False) # save to csv for next step